services:
  windows:
    image: dockurr/windows
    container_name: windows
    environment:
      RAM_SIZE: "8G"
      VERSION: "CUSTOMVERSIONPLACEHOLDER"
      USERNAME: "USERNAMEPLACEHOLDER"
      PASSWORD: "PASSWORDPLACEHOLDER"
      XRES: "1920"
      YRES: "1080"
    devices:
      - /dev/kvm
    volumes:
      - /mnt:/storage
      - ./shared:/shared
      - ./oem:/oem
    cap_add:
      - NET_ADMIN
    ports:
      - 2233:22
      - 8006:8006
      - 3389:3389/tcp
      - 3389:3389/udp
    stop_grace_period: 2m
