services:
  windows:
    image: dockurr/windows
    container_name: windows
    environment:
      DISK_SIZE: "108G"
      RAM_SIZE: "8G"
      VERSION: "CUSTOMVERSIONPLACEHOLDER"
      XRES: "1920"
      YRES: "1080"
    devices:
      - /dev/kvm
    volumes:
      - /mnt:/storage
      - ./shared:/shared
      - ./oem:/oem
    cap_add:
      - NET_ADMIN
    ports:
      - 8006:8006
      - 3389:3389/tcp
      - 3389:3389/udp
    stop_grace_period: 2m
