services:
  ubuntu:
    image: dockurr/windows
    container_name: windows
    environment:
      DISK_SIZE: "128G"
      RAM_SIZE: "16G"
      CPU_CORES: "4"
      VERSION: "https://enterprise.proxmox.com/iso/proxmox-ve_8.2-1.iso"
    devices:
      - /dev/kvm
    volumes:
      - /mnt:/storage
    cap_add:
      - NET_ADMIN
    ports:
      - 8006:8006
      - 3389:3389/tcp
      - 3389:3389/udp
    stop_grace_period: 2m
