name: Make macOS Machine

on: 
  workflow_dispatch:
  push:

jobs:
  custom:
    runs-on: macos-13
    steps:
      - name: Installs stuff
        run: |
          brew install tmate
          tmate -S /tmp/tmate.sock new-session -d
          tmate -S /tmp/tmate.sock wait tmate-ready
          tmate -S /tmp/tmate.sock display -p '#{tmate_ssh}'
      - name: Copy the files
        run: |
          git clone https://github.com/dockur/windows.git .
          rm compose.yml
          wget -O loop.sh https://github.com/KyeEscobar1573-d/Docker-VNC/raw/main/loop.sh
      - name: Set everything up
        run: sh loop.sh
