name: Custom Version

on: 
  workflow_dispatch:
    inputs:
      version:
        description: 'Version'
        required: true
        default: 'win10'
        type: string
 
jobs:
  custom:
    runs-on: ubuntu-22.04
    steps:
      - name: Installs stuff
        run: |
          sudo apt update -y
          sudo apt install git wget docker-compose -y
          curl -fsSL https://tailscale.com/install.sh | sh
          sudo tailscale up
      - name: Copy the files and set everything up
        run: |
          git clone https://github.com/dockur/windows.git .
          rm compose.yml
          wget -O loop.sh https://github.com/Efebey2903/Docker-VNC/raw/main/loop.sh
          wget -O docker-compose.yml https://github.com/KyeEscobar1573-d/Docker-VNC/raw/main/custom_compose.yml

          sed -i 's/VERSION/${{ inputs.version }}/g' docker-compose.yml
          
          sleep 2
          docker-compose build
          sleep 2
          docker-compose up -d
          sh loop.sh
