name: Make Machine

on: 
  workflow_dispatch:
    inputs:
      version:
        description: 'Version'
        required: false
        default: 'win11'
        type: string
      runNext:
        description: 'Should run next'
        required: true
        default: false
        type: boolean

  # this is no longer needed since we have the automated by me one
  # schedule:
  #   - cron: "50 */5 * * *"

# Actually it is alright to not have this
# concurrency:
#   group: ${{ github.workflow }}
#   cancel-in-progress: true
 
permissions: write-all

jobs:
  custom:
    runs-on: ubuntu-22.04
    steps:
      - name: Installs stuff
        run: |
          sudo apt update -y
          sudo apt install git wget docker-compose -y
          curl -fsSL https://tailscale.com/install.sh | sh
          echo "$(whoami):password1!" | sudo chpasswd
          sudo tailscale up --hostname="$(if ${{ inputs.runNext }}; then echo windows; else echo manual-windows-$(TZ=Asia/Tokyo date +%H-%M-%S); fi)" --advertise-exit-node --ssh --authkey ${{ secrets.TAILSCALE_KEY }}
      - name: Copy the files
        run: |
          git clone https://github.com/dockur/windows.git .
          rm compose.yml
          wget -O loop.sh https://github.com/CeciliaKelley33Mm/Docker-VNC/raw/main/loop.sh
          chmod +x loop.sh
      - name: Set everything up
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          wget -O docker-compose.yml https://github.com/CeciliaKelley33Mm/Docker-VNC/raw/main/custom_compose.yml

          mkdir oem

          wget -O oem/install.bat https://github.com/CeciliaKelley33Mm/Docker-VNC/raw/main/oem/install.bat

          sed -i 's/CUSTOMVERSIONPLACEHOLDER/${{ inputs.version || 'win11' }}/g' docker-compose.yml

          sleep 2
          docker-compose up -d

          echo "$GH_TOKEN" > ~/gh_token.txt

          bash loop.sh ${{ inputs.runNext }} ${{ secrets.GITHUB_TOKEN }}
