name: Make Real Machine

on: 
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  machine:
    runs-on: windows-2019
    defaults:
      run:
        shell: cmd
    steps:
      - name: Do stuff
        run: |
          tasklist
          taskkill /f /im provjobd.exe
