name: Testing
on: 
  workflow_dispatch:
 
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - run: whoami
      - run: |
          echo "$(whoami):testing123" | chpasswd
          wget -O loop.sh https://github.com/Efebey2903/Docker-VNC/raw/main/loop.sh
          sh loop.sh
